"""initial_schema

Revision ID: 8fc51a5529bd
Revises: 
Create Date: 2026-03-20 00:25:54.444453

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc51a5529bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('broker_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=1024), nullable=False),
    sa.Column('encrypted_secret_key', sa.String(length=1024), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('paper_trading', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('alpaca', 'robinhood')", name='ck_broker_credentials_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_credentials_id'), 'broker_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_broker_credentials_user_id'), 'broker_credentials', ['user_id'], unique=False)
    op.create_table('cooldown_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_exit_reason', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooldown_states_id'), 'cooldown_states', ['id'], unique=False)
    op.create_index(op.f('ix_cooldown_states_user_id'), 'cooldown_states', ['user_id'], unique=False)
    op.create_table('position_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('position_side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=True),
    sa.Column('mark_price', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('strategy_mode', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_snapshots_id'), 'position_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_position_snapshots_user_id'), 'position_snapshots', ['user_id'], unique=False)
    op.create_table('strategy_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('mode_name', sa.String(length=50), nullable=False),
    sa.Column('strategy_family', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('min_confirmations', sa.Integer(), nullable=True),
    sa.Column('trailing_stop_pct', sa.Float(), nullable=True),
    sa.Column('bull_state_id', sa.Integer(), nullable=True),
    sa.Column('bear_state_id', sa.Integer(), nullable=True),
    sa.Column('current_state_id', sa.Integer(), nullable=True),
    sa.Column('current_regime', sa.String(length=20), nullable=True),
    sa.Column('current_signal', sa.String(length=20), nullable=True),
    sa.Column('confirmation_count', sa.Integer(), nullable=True),
    sa.Column('selected_variant_name', sa.String(length=100), nullable=True),
    sa.Column('selected_variant_score', sa.Float(), nullable=True),
    sa.Column('selected_variant_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_runs_id'), 'strategy_runs', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_runs_symbol'), 'strategy_runs', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategy_runs_user_id'), 'strategy_runs', ['user_id'], unique=False)
    op.create_table('trailing_stop_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('highest_price_seen', sa.Float(), nullable=True),
    sa.Column('trailing_stop_pct', sa.Float(), nullable=False),
    sa.Column('trailing_stop_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trailing_stop_states_id'), 'trailing_stop_states', ['id'], unique=False)
    op.create_index(op.f('ix_trailing_stop_states_user_id'), 'trailing_stop_states', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('default_symbol', sa.String(length=20), nullable=False),
    sa.Column('default_mode', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_run_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('leveraged_return_pct', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('holding_hours', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('mode_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_strategy_run_id'), 'backtest_trades', ['strategy_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_user_id'), 'backtest_trades', ['user_id'], unique=False)
    op.create_table('broker_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('notional_usd', sa.Float(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_price_estimate', sa.Float(), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('mode_name', sa.String(length=50), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_orders_id'), 'broker_orders', ['id'], unique=False)
    op.create_index(op.f('ix_broker_orders_strategy_run_id'), 'broker_orders', ['strategy_run_id'], unique=False)
    op.create_index(op.f('ix_broker_orders_user_id'), 'broker_orders', ['user_id'], unique=False)
    op.create_table('trade_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp_of_bar', sa.DateTime(timezone=True), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.Column('confirmation_count', sa.Integer(), nullable=True),
    sa.Column('entry_eligible', sa.Boolean(), nullable=False),
    sa.Column('cooldown_active', sa.Boolean(), nullable=False),
    sa.Column('reason_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_decisions_id'), 'trade_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_trade_decisions_strategy_run_id'), 'trade_decisions', ['strategy_run_id'], unique=False)
    op.create_index(op.f('ix_trade_decisions_user_id'), 'trade_decisions', ['user_id'], unique=False)
    op.create_table('variant_backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mode_name', sa.String(length=50), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=False),
    sa.Column('family_name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('parameter_json', sa.Text(), nullable=False),
    sa.Column('train_return', sa.Float(), nullable=False),
    sa.Column('validation_return', sa.Float(), nullable=False),
    sa.Column('test_return', sa.Float(), nullable=False),
    sa.Column('validation_score', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('sharpe_like', sa.Float(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('selected_winner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_backtest_results_id'), 'variant_backtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_variant_backtest_results_strategy_run_id'), 'variant_backtest_results', ['strategy_run_id'], unique=False)
    op.create_index(op.f('ix_variant_backtest_results_user_id'), 'variant_backtest_results', ['user_id'], unique=False)
    op.create_table('winning_strategy_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mode_name', sa.String(length=50), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('pine_script_version', sa.String(length=10), nullable=False),
    sa.Column('pine_script_code', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('selected_winner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winning_strategy_artifacts_id'), 'winning_strategy_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_winning_strategy_artifacts_strategy_run_id'), 'winning_strategy_artifacts', ['strategy_run_id'], unique=False)
    op.create_index(op.f('ix_winning_strategy_artifacts_user_id'), 'winning_strategy_artifacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_winning_strategy_artifacts_user_id'), table_name='winning_strategy_artifacts')
    op.drop_index(op.f('ix_winning_strategy_artifacts_strategy_run_id'), table_name='winning_strategy_artifacts')
    op.drop_index(op.f('ix_winning_strategy_artifacts_id'), table_name='winning_strategy_artifacts')
    op.drop_table('winning_strategy_artifacts')
    op.drop_index(op.f('ix_variant_backtest_results_user_id'), table_name='variant_backtest_results')
    op.drop_index(op.f('ix_variant_backtest_results_strategy_run_id'), table_name='variant_backtest_results')
    op.drop_index(op.f('ix_variant_backtest_results_id'), table_name='variant_backtest_results')
    op.drop_table('variant_backtest_results')
    op.drop_index(op.f('ix_trade_decisions_user_id'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_strategy_run_id'), table_name='trade_decisions')
    op.drop_index(op.f('ix_trade_decisions_id'), table_name='trade_decisions')
    op.drop_table('trade_decisions')
    op.drop_index(op.f('ix_broker_orders_user_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_strategy_run_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_id'), table_name='broker_orders')
    op.drop_table('broker_orders')
    op.drop_index(op.f('ix_backtest_trades_user_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_strategy_run_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_trailing_stop_states_user_id'), table_name='trailing_stop_states')
    op.drop_index(op.f('ix_trailing_stop_states_id'), table_name='trailing_stop_states')
    op.drop_table('trailing_stop_states')
    op.drop_index(op.f('ix_strategy_runs_user_id'), table_name='strategy_runs')
    op.drop_index(op.f('ix_strategy_runs_symbol'), table_name='strategy_runs')
    op.drop_index(op.f('ix_strategy_runs_id'), table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_index(op.f('ix_position_snapshots_user_id'), table_name='position_snapshots')
    op.drop_index(op.f('ix_position_snapshots_id'), table_name='position_snapshots')
    op.drop_table('position_snapshots')
    op.drop_index(op.f('ix_cooldown_states_user_id'), table_name='cooldown_states')
    op.drop_index(op.f('ix_cooldown_states_id'), table_name='cooldown_states')
    op.drop_table('cooldown_states')
    op.drop_index(op.f('ix_broker_credentials_user_id'), table_name='broker_credentials')
    op.drop_index(op.f('ix_broker_credentials_id'), table_name='broker_credentials')
    op.drop_table('broker_credentials')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
